services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:v2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/space
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.silverbullet.rule=Host(`silverbullet.hl.lan`)"
      - "traefik.http.routers.silverbullet.entrypoints=websecure"
      - "traefik.http.services.silverbullet.loadbalancer.server.port=3000"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true