services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - ./data:/app/config
      - ./data/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    env_file:
      - .env
    environment:
      - HOMEPAGE_VAR_DOMAIN=${DOMAIN}
      - HOMEPAGE_VAR_SERVER_IP=${SERVER_IP}
      - HOMEPAGE_VAR_JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - HOMEPAGE_VAR_ADGUARD_USERNAME=${ADGUARD_USERNAME}
      - HOMEPAGE_VAR_ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
      - HOMEPAGE_VAR_MINIFLUX_API_KEY=${MINIFLUX_API_KEY}
      - HOMEPAGE_VAR_PORTAINER_API_KEY=${PORTAINER_API_KEY}
      - HOMEPAGE_VAR_TRAEFIK_URL=${TRAEFIK_URL}
      - HOMEPAGE_VAR_PORTAINER_URL=${PORTAINER_URL}
      - HOMEPAGE_VAR_JELLYFIN_URL=${JELLYFIN_URL}
      - HOMEPAGE_VAR_MINIFLUX_URL=${MINIFLUX_URL}
      - HOMEPAGE_VAR_ADGUARD_URL=${ADGUARD_URL}
      - HOMEPAGE_VAR_TRAEFIK_EXTERNAL=https://traefik.${DOMAIN}
      - HOMEPAGE_VAR_PORTAINER_EXTERNAL=https://portainer.${DOMAIN}
      - HOMEPAGE_VAR_JELLYFIN_EXTERNAL=https://jellyfin.${DOMAIN}
      - HOMEPAGE_VAR_SFT_EXTERNAL=https://sft.${DOMAIN}
      - HOMEPAGE_VAR_SILVERBULLET_EXTERNAL=https://silverbullet.${DOMAIN}
      - HOMEPAGE_VAR_MINIFLUX_EXTERNAL=https://miniflux.${DOMAIN}
      - HOMEPAGE_VAR_ROUNDCUBE_EXTERNAL=https://roundcube.${DOMAIN}
      - HOMEPAGE_VAR_SEARXNG_EXTERNAL=https://search.${DOMAIN}
      - HOMEPAGE_VAR_ADGUARD_EXTERNAL=https://adguard.${DOMAIN}
      - HOMEPAGE_VAR_BESZEL_EXTERNAL=https://beszel.${DOMAIN}
      - HOMEPAGE_VAR_SAMBA_EXTERNAL=//${SERVER_IP}:445
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`hl.lan`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true