services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    volumes:
      - ./data:/app/config
      - ./data/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`hl.lan`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true